---
apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: uploader
  name: uploader
  namespace: default
spec:
  ports:
  - name: uploader-3000
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    k8s-app: uploader

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    k8s-app: uploader
  name: uploader
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: uploader
  template:
    metadata:
      labels:
        k8s-app: uploader
      name: uploader
    spec:
      containers:
      - image: windsome/uploader:1.0.1
        name: uploader
        volumeMounts:
        - mountPath: /home/data/uploads
          name: uploaderdata
      volumes:
      - hostPath:
          path: /data/uploads
        name: uploaderdata
